module.exports = {
  bodyBackground: '#31343c',
  bodyColor: '',
  headerBackground: '',
  headerColor: '',
  postBackground: '',
  postTitleColor: '',
  postFooterBackground: '',
  postFooterColor: '',
  postColor: '',
  footerBackground: '',
  footerColor: '',
  navLinkColor: '',
  drawerBackground: '',
}
